name: Build and Deploy to Alibaba Function Compute

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Publish
      run: dotnet publish --no-build -c Release -r linux-x64 -o ./publish

    - name: Prepare Bootstrap
      # change .NET binary name 'devops-app' 
      run: |
        if [ -f bootstrap ]; then
          cp bootstrap publish/
        else
          echo '#!/bin/bash' > publish/bootstrap
          echo './devops-app' >> publish/bootstrap
        fi
        chmod +x publish/bootstrap

    - name: Create Function Zip
      run: |
        cd publish
        zip -r ../function.zip .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: function-package
        path: function.zip
        retention-days: 5
 
  deploy:
    name: Deploy to FC
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: function-package
        
    # 1. Serverless Devs Tool install via npm  
    - name: Install Serverless Devs
      run: npm install -g @serverless-devs/s

    # 2. Alibaba Cloud Access Key Login
    - name: Configure Serverless Devs
      run: |
        s config add --AccessKeyID "${{ secrets.ALIYUN_ACCESS_KEY_ID }}" --AccessKeySecret "${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}" -a default -f

    # 3. Create s.yaml for to deploy
    
    - name: Create s.yaml Configuration
      run: |
        cat <<EOF > s.yaml
        edition: 3.0.0
        name: cicd-deploy
        access: default
        resources:
          function_resource:
            component: fc3
            props:
              region: ${{ secrets.ALIYUN_REGION }}
              functionName: test-nodejs-cicd-function
              runtime: custom.debian10
              code: ./function.zip
              handler: index.handler
              timeout: 60
              memorySize: 512
        EOF

    # 4. Deploy to Alibaba Cloud Function Compute
    - name: Deploy to Alibaba Cloud
      run: s deploy -y
